{
 "title": "AiraHome - Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "id",
    "label": "Heatpump ID",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(\r\n  bucket: \"devices\",\r\n  tag: \"id\",\r\n  start: time(v: 0)\r\n)"
    }
   },
   { "name": "query_time", "query": "${VAR_QUERY_TIME}" },
   {
    "name": "cur_data",
    "query": {
     "query": "from(bucket: \"states\")\r\n  |> range(start: -${query_time})\r\n  |> filter(fn: (r) => r.id == \"${id}\")\r\n  |> last()\r\n  |> group(columns: [\"_measurement\"])                         // Group by measurement so we process each separately\r\n  |> map(fn: (r) => ({                                         // Transform each row\r\n      // If zone tag exists and is not empty, append it to measurement name\r\n      _measurement: if exists(r.zone) and r.zone != \"\" \r\n                        then r._measurement + \"_\" + r.zone\r\n                        else r._measurement,\r\n      _field: r._field,                                       // Keep field name\r\n      kv: r._field + \": \" + string(v: r._value)               // Create \"field: value\" string\r\n  }))\r\n  |> group(columns: [\"_measurement\"])                         // Regroup by updated measurement names\r\n  |> reduce(                                                   // Combine all kv strings per measurement\r\n      fn: (r, accumulator) => ({\r\n        _measurement: r._measurement,                         // Keep measurement name\r\n        fields: if accumulator.fields == \"\"                   // First row in group\r\n                   then \"_measurement: \" + r._measurement + \", \" + r.kv  // Start string\r\n                   else accumulator.fields + \", \" + r.kv      // Append to existing string\r\n      }),\r\n      identity: { _measurement: \"\", fields: \"\" }              // Initial accumulator values\r\n  )\r\n"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"devices\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"heat_pump\" and r.id == \"${id}\")"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "options": {
    "content": "<style>\n    .view_container {\n        display: flex;\n        justify-content: center; /* Horizontally center */\n        align-items: center;    /* Vertically center */\n    }\n    \n    .view_frame {\n        text-align: center;\n        display: block;\n        border: none; /* Remove default iframe border */\n        width: 449.1575px;\n        height: 215.2533px;\n        background-color: #111217;\n    }\n\n</style>\n<script>\n//window.addEventListener(\"load\", function() {\n    var view_frame = document.getElementById('view_frame');\n    var view_container = document.getElementById('view_container');\n    view_frame.addEventListener('load', function() {\n        view_container.style.height = view_container.parentElement.offsetHeight - 6 + \"px\";\n        //view_container.style.width = view_container.parentElement.offsetWidth - 6 + \"px\";\n        if (!view_frame.src) {\n            raw_data = `${cur_data:csv}`.split('_measurement:');\n            data = {};\n            raw_data.forEach(function(measurement) {\n                temp_data = measurement.split(',');\n                if (temp_data.length > 0) {\n                    //console.log(temp_data);\n                    key = temp_data[0].trim();\n                    data[key] = {};\n                    temp_data.slice(1).forEach(function(item) {\n                        if (!item.includes(':')) {\n                            return; // Skip if no colon is found\n                        }\n                        [cur_key, value] = item.split(':', 2);\n                        if (!cur_key || !value) {\n                            return; // Skip if either key or value is missing\n                        }\n                        data[key][cur_key.trim()] = value.trim();\n                    });\n                }\n            });\n            view_frame.src = window.location.protocol + \"//\" + window.location.hostname + \":4001/?data=\" + encodeURIComponent(JSON.stringify(data));\n            window.addEventListener('message', (event) => {\n                if (event.data.action === 'updateIsLoaded') {\n                    view_frame.style.opacity = \"1\";\n                }\n            });\n            \n        }\n    });\n//});\n</script>\n<div id=\"view_container\" class=\"view_container\">\n    <iframe id=\"view_frame\" class=\"view_frame\" style=\"opacity: 0;\">\n        If you are seeing this it means that your browser does not support Iframes. Please use an updated browser...\n    </iframe>\n</div>"
   }
  },
  {
   "title": "Errors",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 2 },
   "targets": [
    {
     "query": "from(bucket: \"states\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"error\")\r\n  |> filter(fn: (r) => r[\"id\"] == \"${id}\")\r\n  |> keep(columns: [\"_time\", \"ccv\", \"severity\"])\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"ccv\"], valueColumn: \"severity\")"
    }
   ]
  },
  {
   "title": "Ambient",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"states\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"heat_pump\")\r\n  |> filter(fn: (r) => r._field == \"current_outdoor_temperature\")\r\n  |> filter(fn: (r) => r.id == \"${id}\")"
    },
    {
     "query": "from(bucket: \"states\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"thermostat\")\r\n  |> filter(fn: (r) => r._field == \"actual_temperature\")\r\n  |> filter(fn: (r) => r.id == \"${id}\")\r\n  |> filter(fn: (r) => r.zone == \"1\")"
    },
    {
     "query": "from(bucket: \"states\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"thermostat\")\r\n  |> filter(fn: (r) => r._field == \"humidity\")\r\n  |> filter(fn: (r) => r.id == \"${id}\")\r\n  |> filter(fn: (r) => r.zone == \"1\")"
    },
    {
     "query": "from(bucket: \"states\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"thermostat\")\r\n  |> filter(fn: (r) => r._field == \"actual_temperature\")\r\n  |> filter(fn: (r) => r.id == \"${id}\")\r\n  |> filter(fn: (r) => r.zone == \"2\")"
    },
    {
     "query": "from(bucket: \"states\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"thermostat\")\r\n  |> filter(fn: (r) => r._field == \"humidity\")\r\n  |> filter(fn: (r) => r.id == \"${id}\")\r\n  |> filter(fn: (r) => r.zone == \"2\")"
    }
   ]
  },
  {
   "title": "Domestic Hot Water",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"states\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"heat_pump\")\r\n  |> filter(fn: (r) => r.id == \"${id}\")\r\n  |> filter(fn: (r) => r._field == \"pump_active_state\")\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: if r._value == \"PUMP_ACTIVE_STATE_DHW\" then 1\r\n              //else if r._value == \"PUMP_ACTIVE_STATE_IDLE\" then 0\r\n              else 0\r\n    }))"
    },
    {
     "query": "from(bucket: \"states\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"heat_pump\")\r\n  |> filter(fn: (r) => r.id == \"${id}\")\r\n  |> filter(fn: (r) => r._field == \"pump_active_state\")\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: if r._value == \"PUMP_ACTIVE_STATE_ANTI_LEGIONELLA\" then 1\r\n              //else if r._value == \"PUMP_ACTIVE_STATE_IDLE\" then 0\r\n              else 0\r\n    }))"
    },
    {
     "query": "from(bucket: \"states\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"heat_pump\")\r\n  |> filter(fn: (r) => r.id == \"${id}\")\r\n  |> filter(fn: (r) => r._field == \"inline_heater_active\")\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: if r._value then .5\r\n              else 0.0\r\n    }))"
    },
    {
     "query": "from(bucket: \"states\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"water_heater\")\r\n  |> filter(fn: (r) => r.id == \"${id}\")\r\n  |> filter(fn: (r) => r._field == \"current_hot_water_temperature\")\r\n"
    },
    {
     "query": "from(bucket: \"states\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"water_heater\")\r\n  |> filter(fn: (r) => r.id == \"${id}\")\r\n  |> filter(fn: (r) => r._field == \"target_hot_water_temperature\")\r\n"
    },
    {
     "query": "// 1. Get first DHW Heating Time\r\npumpOn = from(bucket: \"states\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"heat_pump\")\r\n  |> filter(fn: (r) => r.id == \"${id}\")\r\n  |> filter(fn: (r) => r._field == \"pump_active_state\")\r\n  |> filter(fn: (r) => r._value == \"PUMP_ACTIVE_STATE_DHW\")\r\n  |> first()\r\n  |> keep(columns: [\"_time\"])\r\n\r\n// 2. Get temperature at that time\r\ntemps = from(bucket: \"states\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"water_heater\")\r\n  |> filter(fn: (r) => r.id == \"${id}\")\r\n  |> filter(fn: (r) => r._field == \"current_hot_water_temperature\")\r\n\r\n// join\r\npumpTemp = join(tables: {pump: pumpOn, temp: temps}, on: [\"_time\"])\r\n  |> findRecord(fn: (key) => true, idx: 0) // get single row\r\n\r\n// 3. Replay constant value over full range\r\nfrom(bucket: \"states\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"water_heater\")\r\n  |> filter(fn: (r) => r.id == \"${id}\")\r\n  |> filter(fn: (r) => r._field == \"current_hot_water_temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> map(fn: (r) => ({ r with _value: pumpTemp._value }))\r\n"
    }
   ]
  },
  {
   "title": "Current Thermostats RSSI",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"states\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"thermostat\")\r\n  |> filter(fn: (r) => r.id == \"${id}\")\r\n  |> filter(fn: (r) => r._field == \"rssi\")\r\n  |> last()\r\n"
    }
   ]
  }
 ]
}